source 'https://rubygems.org'

gem 'pry'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'rake'
gem 'thin'

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'

gem 'sinatra-rest-api', path: '../../'
